version: '2'

services:
  db:
    image: postgres:10.1-alpine
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src/tax-calculator-api
    ports:
      - "8000:8000"
    depends_on:
      - db
