TAX_CODE_FOOD = 1
TAX_CODE_TOBACCO = 2
TAX_CODE_ENTERTAINMENT = 3

TAX_TYPE_FOOD = 'Food'
TAX_TYPE_TOBACCO = 'Tobacco'
TAX_TYPE_ENTERTAINMENT = 'Entertainment'

MSG_TAX_CODE_REGISTERED = 'tax code tidak ada di sistem'
MSG_TAX_NAME_MUST_UNIQUE = 'tax name harus unik'
