# Generated by Django 2.0.7 on 2018-09-16 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0002_auto_20180915_0449'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(null=True)),
                ('tax_amount', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=16, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction.Bill')),
                ('tax_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='tax.TaxItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
