# Generated by Django 2.0.7 on 2018-09-15 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bill.Bill')),
                ('tax_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='tax.TaxItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
