# Generated by Django 2.0.7 on 2018-09-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('tax_code', models.SmallIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
            ],
        ),
    ]
