# Generated by Django 2.0.7 on 2018-09-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='taxitem',
            name='total_amount',
        ),
    ]
